version: "3"

services:
    webapp:
        container_name: webapp
        hostname: webapp
        image: laradok:stable-1
        stdin_open: true
        tty: true
#        command: rc-service nginx start && rc-service supervisord start
        volumes:
            -   ./:/var/www/html
            -   ./nginx.conf:/etc/nginx/nginx.conf
            -   ./supervisord.conf:/etc/supervisord.conf
        ports:
            -  80:80

